name: Build and Tests
on: push
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.8.0
          args: install
      - name: Lint with flake8
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.8.0
          poetry_version: 0.12.17
          args: run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.8.0
          poetry_version: 0.12.17
          args: run python -m pytest tests/